# Generated by Django 4.2 on 2025-01-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_profile'),
        ('shop', '0002_profile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
