# Generated by Django 4.2 on 2025-01-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=447)),
                ('price', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('days', models.PositiveSmallIntegerField()),
                ('is_enable', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='magnusplus.package')),
            ],
        ),
    ]
