# Generated by Django 4.2 on 2025-02-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_magnusplus_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='magnusplus_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
